- hosts: dbservers
  become: yes
  vars:
    dbname: devops
    dbuser: mint
    dbpass: 12345

  tasks:
  - name: Ensure mysql installed
    yum: name=mysql-server state=present

  - name: Ensure mysql running
    service: name=mysqld state=started

  - name: Ensure MySQL-pyhton is installed
    yum: name=MySQL-python state=present

  - name: create user named mint
    mysql_user: name={{dbuser}} password={{dbpass}} priv='*.*:ALL' state=present
